words = [
  "ALS",
  "BLAS",
  "CLI",
  "CSR",
  "Cython",
  "Drexel",
  "ILC",
  "LAPACK",
  "NDCG",
  "Optuna",
  "Optuna",
  "RBP",
  "RMSE",
  "TPE",
  "accessors",
  "bytestream",
  "cpus",
  "getstate",
  "gpus",
  "hyperparameters",
  "lenskit",
  "mkdir",
  "mult",
  "nocover",
  "nums",
  "parameterizations",
  "profiler",
  "recommender",
  "seealso",
  "setstate",
  "tbl",
  "wirings",
  "zstd",
]
