[pytest]
log_level=DEBUG
doctest_plus=enabled
filterwarnings =
    default::ResourceWarning
    ignore:::pyarrow[.*]
    ignore:.*matrix subclass.*:PendingDeprecationWarning
    ignore:.*np.asscalar.*:DeprecationWarning
markers =
    eval: mark the test as running the evaluator over custom data
    slow: mark the test as taking a larger-than-usual amount of time
