jobs:
- job: 'WindowsVanilla'
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      # Disabled pending PyArrow
      # Python38:
      #   python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      set PIP_PREFER_BINARY=true
      pip install $(pip.deps)
    displayName: 'Install dependencies'

  - script: |
      python -m pytest --junitxml=build/test-results.xml
    displayName: 'Test LKPY'
  
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'build/test-results.xml'
      testRunTitle: 'Publish test results for Windows Python $(python.version)'
