jobs:
- job: 'LinuxConda'
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        env.file: dev-env-py36.yml
      Python37:
        python.version: '3.7'
        env.file: dev-env-py37.yml
      Python38:
        python.version: '3.8'
        env.file: dev-env-py38.yml
    maxParallel: 4

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: |
      set -x
      conda env create -n lkpy -q -f $(env.file)
    displayName: Create Anaconda environment

  - script: |
      source activate lkpy
      python -V
      numba -s
    displayName: 'Inspect environment'
    
  - script: |
      if [ ! -r ml-100k/u.data ]; then
        wget --no-verbose -O ml-100k.zip http://files.grouplens.org/datasets/movielens/ml-100k.zip
        unzip ml-100k.zip
      fi
    displayName: 'Download ML-100K'

  - script: |
      source activate lkpy
      mkdir -p build
      python3 setup.py build_helper || exit 2
      python3 setup.py build
    displayName: 'Build LKPY'

  - script: |
      source activate lkpy
      # export NUMBA_THREADING_LAYER=omp # Tests don't work with TBB
      export MKL_THREADING_LAYER=tbb
      python3 -m pytest --junitxml=build/test-results.xml --cov=lenskit --verbose
    displayName: 'Test LKPY'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'build/test-results.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - script: |
      source activate lkpy
      env NUMBA_DISABLE_JIT=1 python3 -m pytest --cov=lenskit --cov-append -m 'not slow'
    displayName: 'Non-JIT Test Coverage'

  - template: ./nix-coverage.yml

  - script: |
      source activate lkpy
      cp -r ml-100k doc
      cp -r ml-latest-small doc
      export PYTHONPATH="$PWD"
      python3 -m pytest --nbval-lax doc
    displayName: Validate Documentation Examples
