[tools]
rust = "stable"
usage = "latest"
uv = "latest"
shfmt = "latest"
tombi = "latest"
"pipx:pre-commit" = "4"
cargo-binstall = "latest"
"cargo:cargo-binutils" = "0.3"
perl = { version = "latest", os = ["linux", "macos"] }
hk = "latest"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
github.github_attestations = false
aqua.github_attestations = false

[settings.python]
uv_venv_auto = true

[env]
HK_MISE = 1
