[tools]
rust = "stable"
usage = "latest"
uv = "latest"
shfmt = "latest"
tombi = "latest"
perl = { version = "latest", os = ["linux", "macos"] }
hk = "latest"
pkl = "latest"
taplo = "latest"
dprint = "latest"
yamlfmt = "latest"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
github.github_attestations = false
aqua.github_attestations = false

[settings.python]
# uv_venv_auto = "source"

[env]
HK_MISE = 1
