context:
  name: lenskit
  version: ${{env.get("LK_PACKAGE_VERSION", default="2100.0a0+dev0")}}
  python_min: "3.11"

recipe:
  name: lenskit
  version: ${{ version }}

source:
  - if: version == "2100.0a0+dev0"
    then:
      path: ..
    else:
      path: ../dist/lenskit-${{version}}.tar.gz

build:
  number: 0
outputs:
  - package:
      name: lenskit

    build:
      python:
        version_independent: true
      script:
        - python -m pip install --no-deps --no-build-isolation -vv .

    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler("rust") }}
      host:
        - python ${{ python_min }}.*
        - pip
        - maturin >=1,<2
      run:
        - python >=${{ python_min }}
        - typing-extensions >=4.12,<5
        - pyarrow >=20,<21
        - pandas >=2.0,<3
        - numpy >=1.25,<3
        - scipy >=1.11,<2
        - pytorch >=2.4,<3
        - more-itertools >=9.0
        - threadpoolctl >=3.0
        - structlog >=23.2
        - rich >=13.5,<14
        - pyzmq >=24
        - click >=8.1,<9
        - requests >=2.28,<3
        - psutil >=6
        - py-cpuinfo >=9.0
        - pydantic >=2.7,<3
        - pydantic-settings >=2.8,<3
        - humanize >=4.2,<5
        - prettytable >=3.14,<4
        - xopen >=2.0,<3
        - lazy-loader >=0.4
        - deepmerge >=2.0,<3

    tests:
      - python:
          imports:
            - lenskit
            - lenskit.data
            - lenskit.als
            - lenskit.knn
          pip_check: false
      - script:
          - python -m lenskit --verbose doctor --full
      - script:
          - pytest -m "not slow" tests
        files:
          source:
            - tests/
            - conftest.py
            - data/
            - pipelines/
            - pyproject.toml
        requirements:
          run:
            - pytest >=8.2,<9
            - pytest-benchmark =4
            - pytest-doctestplus >=1.2.1,<2
            - hypothesis >=6.16
            - pyyaml ~=6.0

  - package:
      name: lenskit-funksvd
    build:
      noarch: python
      script:
        - "true"
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - lenskit >=2025.3

  - package:
      name: lenskit-sklearn
    build:
      noarch: python
      script:
        - "true"
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('lenskit') }}
        - scikit-learn >=1.2,<2
    tests:
      - python:
          imports:
            - lenskit.sklearn.svd
          pip_check: false
      - script:
          - pytest -m "not slow" tests/sklearn
        files:
          source:
            - tests/
            - conftest.py
            - data/
            - pyproject.toml
        requirements:
          run:
            - pytest >=8.2,<9
            - pytest-benchmark =4
            - pytest-doctestplus >=1.2.1,<2
            - hypothesis >=6.16
            - pyyaml ~=6.0

  - package:
      name: lenskit-implicit
    build:
      noarch: python
      script:
        - "true"
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('lenskit') }}
        - implicit >=0.7.2
    tests:
      - python:
          imports:
            - lenskit.implicit
          pip_check: false
      - script:
          - pytest -m "not slow" tests/implicit
        files:
          source:
            - tests/
            - conftest.py
            - data/
            - pyproject.toml
        requirements:
          run:
            - pytest >=8.2,<9
            - pytest-benchmark =4
            - pytest-doctestplus >=1.2.1,<2
            - hypothesis >=6.16
            - pyyaml ~=6.0

  - package:
      name: lenskit-hpf
    build:
      noarch: python
      script:
        - "true"
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('lenskit') }}
        - hpfrec =0.2
    tests:
      - python:
          imports:
            - lenskit.hpf
          pip_check: false
      - script:
          - pytest -m "not slow" tests/hpf
        files:
          source:
            - tests/
            - conftest.py
            - data/
            - pyproject.toml
        requirements:
          run:
            - pytest >=8.2,<9
            - pytest-benchmark =4
            - pytest-doctestplus >=1.2.1,<2
            - hypothesis >=6.16
            - pyyaml ~=6.0

  - package:
      name: lenskit-gnn
    build:
      noarch: python
      script:
        - "true"
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('lenskit') }}
        - torch-geometric >=2.6,<3
    tests:
      - python:
          imports:
            - lenskit.graphs.lightgcn
          pip_check: false
      - script:
          - pytest -m "not slow" tests/graphs
        files:
          source:
            - tests/
            - conftest.py
            - data/
            - pyproject.toml
        requirements:
          run:
            - pytest >=8.2,<9
            - pytest-benchmark =4
            - pytest-doctestplus >=1.2.1,<2
            - hypothesis >=6.16
            - pyyaml ~=6.0

  - package:
      name: lenskit-tune
    build:
      noarch: python
      script:
        - "true"
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('lenskit') }}
        - ray-tune >=2.42,<3
    tests:
      - script:
          - lenskit tune --help

about:
  license: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

  homepage: https://lenskit.org
  repository: https://github.com/lenskit/lkpy
  documentation: https://lkpy.lenskit.org/

extra:
  recipe-maintainers:
    - mdekstrand
