[search]
max_points = 30
list_length = 1000
max_epochs = 50
metric = "RBP"
num_gpus = 1

[space.scorer]
embedding_size_exp = { type = "int", min = 3, max = 10 }
regularization = { type = "float", min = 1e-4, max = 10, scale = "log" }
learning_rate = { type = "float", min = 1e-3, max = 1e-1, scale = "log" }
negative_count = { type = "int", min = 1, max = 5 }

[pipeline]
file = "flexmf-bpr.toml"
