[search]
method = "optuna"
max_points = 30
list_length = 1000
metric = "RMSE"

[space.scorer]
max_nbrs = { type = "int", min = 1, max = 100 }
min_nbrs = { type = "int", min = 1, max = 10 }
min_sim = { type = "float", min = 1e-12, max = 0.2 }

[pipeline]
file = "iknn-explicit.toml"
