[meta]
name = "lightgcn-bpr"

[options]
base = "std:topn"

[components.scorer]
class = "lenskit.flexmf.FlexMFImplicitScorer"

[components.scorer.config]
loss = "pairwise"
embedding_size = 32
convolution_layers = 2
