from __future__ import annotations

import pyarrow as pa

from lenskit.data.matrix import SparseRowArray

class RowColumnSet:
    def __init__(self, matrix: SparseRowArray): ...
    def contains_pair(self, row: int, col: int) -> bool: ...

class NegativeSampler:
    def __init__(self, rc_set: RowColumnSet, users: pa.Int32Array, tgt_n: int): ...
    def num_remaining(self) -> int: ...
    def accumulate(self, items: pa.Int32Array, force: bool): ...
    def result(self) -> pa.Int32Array: ...
