name: Build Packages
on:
  push:
    branches:
      - master
    tag:
  release:
    types: [published]
jobs:
  sdist:
    name: Build source packages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python packaging deps
      run: pip install -U pip setuptools wheel

    - name: Build source dist
      run: python setup.py sdist --format gztar,zip

    - name: Save archive
      uses: actions/upload-artifact@v1
      with:
        name: pypi-pkgs
        path: dist
      
  conda:
    name: Build Packages on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    if: false
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        include:
        - platform: macos
          condaplat: osx-64
        - platform: ubuntu
          condaplat: linux-64
        - platform: windows
          condaplat: win-64

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Fix Conda Perms
      if: runner.os == 'macOS'
      run: sudo chown -R $USER $CONDA/

    - name: Set Conda path
      run: echo "::add-path::$CONDA/condabin"
      shell: bash

    - name: Install Conda deps
      run: |
        conda update -qy --all
        conda install -qy conda-build

    - name: Build Conda packages
      run: |
        cd conda
        conda build -c lenskit .

    - name: Copy Conda packages
      run: |
        $ddir = (Join-Path dist ${{matrix.condaplat}})
        $bld = (Join-Path $env:CONDA conda-bld ${{matrix.condaplat}})
        New-Item -Type Directory $ddir
        Get-ChildItem $bld |Copy-Item -Destination $ddir
        Get-ChildItem -Recurse dist
      shell: pwsh
      
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: conda-pkgs
        path: dist

  upload:
    name: Publish packages
    runs-on: ubuntu-latest
    needs: 
      - sdist
      # - conda

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      # - name: Set Conda path
      #   run: echo "::add-path::$CONDA/condabin"
      #   shell: bash

      # - name: Install Conda deps
      #   run: |
      #     conda update -qy --all
      #     conda install -qy anaconda-client twine keyring rfc3986

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python deps
        run: |
          pip install twine keyring rfc3986

      - name: Fetch PyPI artifacts
        uses: actions/download-artifact@v2
        with:
          name: pypi-pkgs
          path: dist

      # - name: Fetch Conda artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: conda-pkgs
      #     path: dist

      - name: List dist dir
        run: ls -R dist

      - name: Publish PyPI packages
        if: github.event_name == 'release'
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate base
          twine upload dist/lenskit*.zip
        shell: bash
        env:
          TWINE_NON_INTERACTIVE: y
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

      # - name: Publish Conda packages
      #   if: github.event_name == 'release'
      #   run: |
      #     source $CONDA/etc/profile.d/conda.sh
      #     conda activate base
      #     anaconda upload -u lenskit dist/*/lenskit*.tar.bz2
      #   shell: bash
      #   env:
      #     ANACONDA_API_TOKEN: ${{ secrets.CONDA_TOKEN }}

      # - name: Publish dev Conda packages
      #   if: github.event_name == 'push'
      #   run: |
      #     source $CONDA/etc/profile.d/conda.sh
      #     conda activate base
      #     anaconda upload -u lenskit -l dev dist/*/lenskit*.tar.bz2
      #   shell: bash
      #   env:
      #     ANACONDA_API_TOKEN: ${{ secrets.CONDA_TOKEN }}
