name: Static Checks
on:
  push:
    branches:
      - main
      - series/*
      - future/*
  pull_request:

concurrency:
  group: check-${{github.ref}}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Check pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧑🏻‍💻 Set up mise
        uses: jdx/mise-action@v4
        with:
          cache: false

      - name: ✅ Check that pre-commit is clean
        run: |
          hk check --all

  lint:
    name: Annotate with lint failures
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🕶️ Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
          activate-environment: true

      - name: Install packages
        run: uv sync --only-dev

      - name: 🐜 Check source code lint rules
        id: lint
        run: ruff check --output-format=github
